### PR TITLE
Dropfile Component, Internationalization, Tooltips.

### LINKED ISSUE #43: Support drag and drop into main viewer window

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Fixes #43, #47 and #49. 

- **DropFile**
  - Created component to upload files either by dropping or selecting them.
  - Maybe the endpoint of the DropFile [here](https://github.com/opensim-org/opensim-viewer/blob/38e8486f8fcea925db501df7cc25a09c7c95d239/src/components/Components/DropFile.tsx#L99) can be a parameter of the component.
  - The files are uploaded, but not handled. We need to handle it so it is shown in the viewer.
- **Internationalization**
  - Using i18next library.
  - Using plurals.
  - Translated into Spanish for testing (do we want to translate to other languages? We expect users to upload and navigate information in English)
- **Tooltips**
  - Created tooltips for icons.

### CODE REVIEW

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz Please let me know when this is ready for review. Build failing as of now. Thank you

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I think I fixed the problem here. There was a test not passing (since it was looking for a text that is now provided by the localization library), and a warning.

I also fixed a minor issue with the drop file component.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz Curious how to switch language or how to decide which language to use?

**Comment by AlbertoCasasOrtiz** [comment]
I added a plugin that automatically detects the language, but for testing purposes you can specify a default language in the src/internationalization/i18n.js file, in line 10.

**Review by aymanhab — APPROVED** [review]
LGTM, thanks @AlbertoCasasOrtiz

**Pull request merged**
