### PR TITLE
embed gltf_url in viewer url

### PR DESCRIPTION
**Pull request by aymanhab**
The goal here is to be able to share the view with a single link, so the receiver can view, navigate the model and animations without having to explicitly visit the viewer site or log in.

### CODE REVIEW

**Comment by aymanhab** [comment]
As of now refreshing the page or sharing the link doesn't work. Investigating

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz I fixed this so that when you upload a file you can share the url with others without login, please try this URL
https://fix-url-mapping.d7iaa9a9lxtm6.amplifyapp.com/viewer/https%3A%2F%2Fs3.us-west-2.amazonaws.com%2Fopensim-viewer-public-download%2Fbouncing_block.gltf

**Comment by AlbertoCasasOrtiz** [comment]
Looks like it is working, I can see the bouncing_block.gltf model.

**Comment by aymanhab** [comment]
Perfect, thank you. If you can review that would be great to merge into master.

**Review by AlbertoCasasOrtiz — APPROVED** [review]
LGTM! Only thing I noticed is that when you click on the "viewer" button at the top, the correct model is opened, but the url is "http://localhost:3000/viewer", so it cannot be copied and shared. (I tested in both local and deployed versions). Maybe we can address this on a different issue.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz will merge this and open an issue to address the viewer button separately (basically it has a hardcoded link to /viewer regardless of context, need to be context aware)

**Pull request merged**
