### PR TITLE
Connect toolbar buttons

### PR DESCRIPTION
**Pull request by aymanhab**
Zoom in/out, snapshot

### CODE REVIEW

**Comment by aymanhab** [comment]
This PR, connects the actions to zoom in/out and print buttons and renames OpenSimModel to OpenSimScene which is the actual functionality (will change file names later. Thoughts?

**Comment by aymanhab** [comment]
needs review when you have a chance @AlbertoCasasOrtiz Thank you

**Review by AlbertoCasasOrtiz — APPROVED** [review]
I have just tested it and reviewed the code and everything is looking good and working.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz 👍

**Pull request merged**
