### PR TITLE
Autoplay animations if included in gltf file, fix arm26_elbow_flex.gltf

### PR DESCRIPTION
**Pull request by aymanhab**

### CODE REVIEW

**Comment by aymanhab** [comment]
When you pick the model for marker data it now animates, we can use that to demo the trc, grf, c3d file conversion for now until models and animations are implemented

**Comment by aymanhab** [comment]
For your review @AlbertoCasasOrtiz Eventually we want to customize play speed/repeat/fade etc. with ui but that's useful to check if animations are exported properly

**Comment by aymanhab** [comment]
Not sure what you mean by weird movement, but if a gltf contains an animation it should autoplay, others should have no effect. Only file in repo with stored animation is the arm26 marker data file. Please let me know if anything else has changed. 

The PR is still pending your approval.

**Comment by aymanhab** [comment]
pending approval @AlbertoCasasOrtiz

**Review by AlbertoCasasOrtiz — APPROVED** [review]

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab Sorry, I though I did this yesterday. I just approved it.

**Pull request merged**
