### PR TITLE
Format model view page

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
**Do not merge until #24 is merged, I accidentally created this branch from #24 instead of main.**

I have formatted the model view page using cards. Right now, the demo data is hardcoded.

We have to define metadata for the models (name, description, authors, license... etc).

Instead of showing an image of the model, I have added a previsualization of the model using threejs, similarly to some 3D model pages.

### CODE REVIEW

**Review by aymanhab — CHANGES_REQUESTED** [review]
Will wait for the other PR to get merged so the changes are not entangled. My thoughts:
we should create a json file for now with the data/info/links for "featured" models, eventually we can pull these from a database without touching the front-end.
I'd also would move State that needs to be shared between components into the newly created ViewerState class so that state is not sprinkled across components and out of control. Maybe better to discuss in person.

**Comment by AlbertoCasasOrtiz** [comment]
I have just created a json file with the models' information and I am going to review and test the PR with the ViewerState. Once we merge that PR I will update this branch and move states to the ViewerState.

**Comment by aymanhab** [comment]
Perfect, the other PR has been merged to feel free to proceed on this one. Thank you

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab, I have merged from main and resolved conflicts. In this PR I have moved all of the states to the new class ViewerState and I am using everything from there. I also removed the gizmos from the models preview in the model showcase page, and made it functional (Now, you can click in the title of each model and actually see it in the viewer).

**Comment by aymanhab** [comment]
Looks great, thanks much @AlbertoCasasOrtiz 🥇 Will merge now to reformat and merge my own changes and open an issue to beef up the testing for the added functionality. Thanks again

**Review by aymanhab — APPROVED** [review]

**Pull request merged**
