### PR TITLE
Dockerize backend

### PR DESCRIPTION
**Pull request by aymanhab**
This PR creates a Docker container to run the backend needed for the viewer

### CODE REVIEW

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz My understanding is that all the pieces are there and the call to docker-compose up throws no errors but I can't connect to the server, any idea what maybe wrong based on your OpenCap experience? How are the databases and superusers created/migrated?

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz this seems to work on local docker as expected, do you know how we test deployment either on aws or elsewhere with our current accounts/apps? Thank you

**Comment by AlbertoCasasOrtiz** [comment]
Hi @aymanhab. In OpenCap, the database is stored in [Amazon RDS](https://aws.amazon.com/es/rds/). Then, the docker instance connects to that database, and we can manage the database data independently (backups, updates... etc).

The backend per se is stored in [Amazon EC2](https://aws.amazon.com/es/ec2/) by using a docker container. In opencap all of this deployment proccess is automatically done by using terraform, but this is a part of opencap I have not explored enough yet. Maybe we should talk with Antoine and Scott about this when we are ready to deploy, and with Henry about creating the EC2 and RDS instances for opensim-viewer.

**Comment by aymanhab** [comment]
ok, thanks @AlbertoCasasOrtiz Can you please approve this so we can merge as it breaks nothing anyway and so we can test deployment from the master branch? Thank you

**Review by AlbertoCasasOrtiz — APPROVED** [review]
LGTM. I have a question. Should we make the DockerFile to run tests? This way we could detect errors anytime we deploy in the future. We can do this in another PR if you think it is a good idea.

**Comment by aymanhab** [comment]
Good question @AlbertoCasasOrtiz Not sure what's the convention. In my mind, Docker is a packaging mechanism, the Docker file makes sure we can import the libraries in python/conda to verify that the packaging works, the testing logic  probably should live somewhere else so it's not entangled but having an entry point to it from the Dockerfile would be a good idea. I think this can go in a separate PR so we can explore deployment

**Pull request merged**
