### PR TITLE
Move Floor into a separate Component 

### PR DESCRIPTION
**Pull request by aymanhab**
Refactor texture loading to happen within a component loading

### CODE REVIEW

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz for your review

**Comment by aymanhab** [comment]
fixes #107

**Review by AlbertoCasasOrtiz — APPROVED** [review]
Working perfectly now. That was a good solution!

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz

**Pull request merged**
