### PR TITLE
Start backend development

### PR DESCRIPTION
**Pull request by aymanhab**

### CODE REVIEW

**Comment by aymanhab** [comment]
As of now the conversion script is stand alone, once we have a front end to drag-drop or file menu will hookup then. For your review @AlbertoCasasOrtiz

**Comment by AlbertoCasasOrtiz** [comment]
Looks good to me. I was thinking if it could be useful to have a small colab notebook for the conversor, it would take a few minutes to adapt it.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz Defnitely will do the notebook as well as a separate issue

**Comment by aymanhab** [comment]
You need to approve the PR though so I can merge it @AlbertoCasasOrtiz

**Review by AlbertoCasasOrtiz — APPROVED** [review]

**Comment by AlbertoCasasOrtiz** [comment]
Done. Sorry I forgot about clicking approve.

**Comment by aymanhab** [comment]
Thanks, Issue opened here https://github.com/opensim-org/opensim-viewer/issues/46

**Pull request merged**
