### PR TITLE
Modify front end to maintain user id and pass it to backend lambda

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
gltf converted files in lambda are uploaded as:

<user_uuid>/<file_name>.gltf

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
Hi @aymanhab, latest changes to the lambda function are here. I am not sure if it will work since I could not push it. When I go to the last step of push instructions, it loops on `Retrying in X second/s`... and then stops. Could it be I do not have permissions to push to the container?

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz this is ready for review and testing, thank you

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
Tested on amplify and it is working for me. The user folder is being created properly and the model is shown.

I tried to approve the PR but it says "Pull request authors can’t approve their own pull request".

**Review by aymanhab — APPROVED** [review]
Approving per @AlbertoCasasOrtiz review. Thank you

**Pull request merged**
