### PR TITLE
Lambda docker

### PR DESCRIPTION
**Pull request by aymanhab**
Create Docker file to use backend as aws lambda function

### CODE REVIEW

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz This PR refactors the backend to run in Docker container invoked from aws lambda

**Review by AlbertoCasasOrtiz — COMMENTED** [review]
The changes in the code LGTM. Do you have a link to the deployed version in AWS so I can test it there?

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz I'm reworking the lambda function to make it operate behind an API thus allowing it to be invoked synchronously and also to allow for sharing/embedding down the road. Should have it all wired up by tomorrow at the latest.

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz this PR still pending your approval. Thank you

**Review by AlbertoCasasOrtiz — APPROVED** [review]
LGTM. Sorry, I had the files marked as reviewerd but looks like I forgot to approve.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz

**Pull request merged**
