### PR TITLE
Data persistence

### LINKED ISSUE #50: Data persistence issues.
If you open a model in the model selector, and then go to the viewer, the latest selected model is not loaded, but the default one.

If you change theme and navigate to viewer or model list, the latest theme is not loaded, but it is dark.

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Fixed problem of states not being consistent when navigating the app.

Fixes #50.

### CODE REVIEW

**Review by aymanhab — DISMISSED** [review]
@AlbertoCasasOrtiz I see that the problem is fixed but it's not clear why, can you explain either on the PR or by adding comments in the code so future changes don't break the fix. Thank you

**Comment by AlbertoCasasOrtiz** [comment]
Sure, in react when you use Button, you are triggering a full page reload to the link specified in href, which re-initializes the states. That is why the states where not persistent when navigating the application even when using mobx.

However, if you use NavLink, it just renders the component specified in the routers defined in the [App.tsx](https://github.com/opensim-org/opensim-viewer/blob/9208b176816093e17eb8b5714354af0dee680af5/src/App.tsx#L41) file, instead of refreshing the full page. This way, the states are not re-initialized, and thus, preserved during the session.

The only problem now is that we are not able to preserve the state if the user refresh the page. Looks like a common way of doing this is using [localStorage](https://blog.logrocket.com/using-localstorage-react-hooks/). In the link it even mentions that it is commonly used for tasks like selecting dark mode, so the user selection is preserved even after closing the browser.

Another option would be to implement user's profiles and save user preferences in a dababase in the backend, but it would not show user preferences if they are not logged in.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz for the fix and explanation. I resolved merge conflicts and will merge soon.

**Review by aymanhab — APPROVED** [review]
LGTM

**Pull request closed without merging**
