### PR TITLE
Recording canvas in webm format.

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Implemented button for recording canvas in the viewer page. Currently, the backend is not involved, but it only generates webm format.

Thigs to do:

- [x] Give feedback that indicates if we are recording (Maybe a red circle at top left/right, or change color of record button to red?)
- [x] Allow download in more formats (mp4 should be enough, as we have discussed in the past)
- [x] Add left menu tab with export options, similar to blender (name of file, export location, export format... for video and images too?)
- [x] Address incompatibility with recording library causing CI to fail.
- [x] Add some kind of loading indicator while video is generating (Overlay?)
- [ ] Address warning thrown by ffmpeg library.

Tasks 1 and 3 should be easy. For 2 I have two options:

1. Doing the conversion on browser using libraries like https://github.com/ffmpegwasm/ffmpeg.wasm
2. Doing the conversion on server using libraries like https://github.com/kkroening/ffmpeg-python

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I am working on the tasks from my previous comment. Especially on converting into MP4.

Another issue is that the library I use to record the canvas is complaining about compatibility with our environment, but I forced the install locally and it worked. I am going to add it to the list of tasks and will solve that as well.

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz Thanks for working on this, much appreciated. Maybe we can discuss the options and pros/cons of various packages when you come as making videos that are smooth and in a widely usable format is one of the big draws of the new visualizer. Cheers

**Comment by AlbertoCasasOrtiz** [comment]
Current version failing in CI because warnings. Will fix that.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @aymanhab. I think this should be completed now. The only thing remaining would be "Address warning thrown by ffmpeg library.". This is the warning thrown by ffmpeg that is causing CI to fail.

Since this is not something we can fix ourselves, should we disable "Treating warnings as errors" in netlify?
I don't have access to it, but according to the error log, setting process.env.CI in netlify to false should be enough.

I think next step could be https://github.com/opensim-org/opensim-viewer/issues/115, since this way I could better notify users when the application is recording or processing the video.

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz I'll deploy this branch on aws to see if that goes thru and then we can merge and handle the conflicts and netlify build later. Build is available here https://recording-canvas.d7iaa9a9lxtm6.amplifyapp.com/

**Comment by AlbertoCasasOrtiz** [comment]
I just tested in the deploy on PC and its working as expected. I tested yesterday on phone and the push notifications are occluding the buttons, so you cannot stop recording. I think we should create a new issue to address this. Maybe we can make the push notifications dismissible at least in phone.

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz the build on aws looks fine but now there're merge conflicts, can you merge master into this branch? Thank you

**Review by aymanhab — APPROVED** [review]
LGTM

**Pull request merged**
