### PR TITLE
Fix style prettier

### PR DESCRIPTION
**Pull request by aymanhab**
Added .prettierrc configuration file to bring formatting/styling uniformity.

### CODE REVIEW

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz I added a configuration file and reformatted all the pages accordingly. I don't feel strongly about the specfifcs of the format, just having a common format. If there's something there you don't like let me know or modify the configuration file and rerun the pages through it (in vscode, use right-mouse-click format document to see the effect). Thank you.

**Comment by AlbertoCasasOrtiz** [comment]
LGTM. I think the current format looks good.

The only thing is that the default tabwidth in vs code is 4 and in the configuration file it is 2, but I believe vs code automatically adapt to it by observing the files (and maybe the configuration file). This should not be a problem.

**Review by AlbertoCasasOrtiz — APPROVED** [review]

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz I was debating tab width and have no-issue switching to 4 spaces, so will do and refresh. Thanks for the prompt feedback

**Review by AlbertoCasasOrtiz — APPROVED** [review]
Looks good to me!

**Pull request merged**
