### PR TITLE
Call generateDecorations twice for fixed and non-fixed geometry

### PR DESCRIPTION
**Pull request by aymanhab**

### CODE REVIEW

**Comment by aymanhab** [comment]
Contact and wrapping surfaces were not displayed because generateDecorations must be called twice on the model. Now fixed but we exclude GeometryPath as not ready to handle yet

**Comment by aymanhab** [comment]
We can use a few more layers for Contact and Wrapping and muscles for finer grain control at some point

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz for your review when u have a chance. Thank you

**Comment by aymanhab** [comment]
Need to update i18n for spanish

**Review by AlbertoCasasOrtiz — CHANGES_REQUESTED** [review]
Hi @aymanhab, everything seems to work properly. The only thing I detected is that if you import a new model, and try to select any object manually, it is not being selected. However if you do it from the tree, it works.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz please open an issue and I'll address with the cleanup when switching models (issue #87)

**Comment by aymanhab** [comment]
Issue #96 has been added to address selection, which is unrelated to this PR. If you agree @AlbertoCasasOrtiz please approve this PR. Thank you

**Review by AlbertoCasasOrtiz — APPROVED** [review]

**Review by AlbertoCasasOrtiz — APPROVED** [review]
LGTM!

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz

**Pull request merged**
