### PR TITLE
Implement layers

### PR DESCRIPTION
**Pull request by aymanhab**
Support layers under the hood, and tie the check boxes under the Visualization "eye" tool to the layers of "Bodies->Mesh" and "Markers", note that this relies on data written by the latest exporter so older/prebaked models will not work out of the box.

### CODE REVIEW

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz This PR includes the changes to support model files as well as various fixes in addition to layers in case you want to target one PR/build to test/integrate. Issues I'm aware of:

- [ ] Jest failure
- [ ] Selection box doesn't show up on switching to a dropped model (works on featured models)
- [ ] We need to cleanup/dispose of scene if user picks "Remove" from the drop file dialog.
- [ ] Axes and some geometry types are not yet supported (ellipse, torus, line, text?)

I haven't tested internationalization but if you can it would be great.
Also any status updates on charting? Maybe open an issue and link to the relevant issue on the sprint.

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz for your review

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz also based on your experience with OpenCap and AddBiomechanics we should come up with a unifying zip file (.osimz) that contains model/geometry/data/results with a json file describing the layout so models with arbitrary geometry can be shown and data from multiple files can be integrated into one view. If this doesn't exist please open an issue and we'll discuss. Thank you

**Comment by aymanhab** [comment]
One more thing, only limited set of geometry files are placed on backend, pending the zip file format/plans

**Comment by nickbianco** [comment]
> @AlbertoCasasOrtiz also based on your experience with OpenCap and AddBiomechanics we should come up with a unifying zip file (.osimz) that contains model/geometry/data/results with a json file describing the layout so models with arbitrary geometry can be shown and data from multiple files can be integrated into one view. If this doesn't exist please open an issue and we'll discuss. Thank you

@aymanhab or @AlbertoCasasOrtiz will file an issue for this feature.

**Review by AlbertoCasasOrtiz — APPROVED** [review]
LGTM! Everything seems to work.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz , I'll merge now but we need to address the issues above either here or as separate issues. Your call.

**Pull request merged**
