### PR TITLE
Remove D-key handler, use appbar instead

### PR DESCRIPTION
**Pull request by aymanhab**
Avoid accidentally switching theme by pressing 'D' while typing username/password or elsewhere

### CODE REVIEW

**Comment by aymanhab** [comment]
Fix issue #77

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz for your review

**Review by AlbertoCasasOrtiz — APPROVED** [review]
LGTM, the issue is fixed.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz

**Pull request merged**
