### PR TITLE
WIP - Fix vertical scrollbar

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Things done:
 - [x] Automatically infer size of bottom bar (#145)
 - [x] Restructure to avoid problems with vertical negative margins (was it due to nested stacks?)
 - [x] Decide if we want two rows or one.
 - [x] Info button background now with theme (#147)
 - [x] Ask user to switch to landscape in phones (not forcing it). (Could solve or make easier #22?)
 - [x] Implemented fullScreen mode for better experience in phones (#34)
 - [x] Fixed problem with background color in themes.
 - [x] Fixed size of elements in bottom bar.
 - [x] Make floating buttons relative to elements, and not to display borders, to avoid problems.

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab The bottom bar is starting to feel too crowded. Should we move the control buttons (zoom, rotate, record... etc) otherwhere, and keep animation control at bottom bar?

I separated it into two different rows (to test if inferring size of bottom bar works), but I am not convinced.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz My thoughts:
What do you think of replicating the look of the GUI where some buttons are floating with transparent background, (zoom, camera) while bottom-bar is animation control similar to the app/GUI toolbar? That would give us more room. Also we can remove the border/label of the animation name to make it slimmer

**Comment by AlbertoCasasOrtiz** [comment]
Thank you @ayman. I think having controls as floating elements as in GUI is a great idea and I already implemented it. Also, I fixed some more things that I found in the app (see description of PR). This PR is starting to get bigger, so once I complete the last task in the description of the PR, I think we can test and merge.

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz that's exciting. Sure full screen would be helpful for demo purposes if not too much work.

**Comment by AlbertoCasasOrtiz** [comment]
@AlbertoCasasOrtiz I think everything should be good now. The only thing is that I added the floating buttons as row instead of column to avoid it occluding the GizmoViewport.

**Review by aymanhab — APPROVED** [review]
Looks great, thanks @AlbertoCasasOrtiz 👍

**Pull request merged**
