### PR TITLE
Handle model change

### PR DESCRIPTION
**Pull request by aymanhab**
This change forces the camera to zoom-out/refocus the whole scene when a new model is loaded. Fixes issue #87

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
I tested this locally and it works when I load new models, but when trying to open a pre-baked model from the model showcase it shows the model with no textures.

The only prebaked model that I managed to open properly at some point was MarkerData, but after exploring other models in the model showcase it is not showing anymore. It throws `Could not load tile.jpg: undefined)`, but the file is present.

**Comment by aymanhab** [comment]
Packaged models will need to be recreated (through downloading gltf files so that annotations for layers and materials are regenerated with the latest defaults. That said the missing texture file is a bit harder to explain. Let me know how to help move this through and thanks for testing @AlbertoCasasOrtiz

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz When I wait on the build for a while it starts acting correctly with showing the floor and fog and using the updated leg39 and pendulum models. Did you have any luck running in dev mode to get to the source of the issue?

**Comment by aymanhab** [comment]
This was subsumed in the PR #105 so will close

**Pull request closed without merging**
