### PR TITLE
opensim-viewer django backend

### LINKED ISSUE #53: Create django backend
This will provide of a basic API in which users can create an User and upload models, that can later be downloaded and shown in the frontend. Once this is finished, we only have to connect the frontend.

- [x] [Environment Creation with YML file](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html).
- [x] Use of [Django Rest Framework](https://www.django-rest-framework.org/).
- [x] Method to Create [ERD Diagrams](https://www.wplogout.com/export-database-diagrams-erd-from-django/) of the database.
- [x] Definition of User.
- [x] Definition of Model.
- [x] [Admin Page Customization](https://realpython.com/customize-django-admin-python/#customizing-the-django-admin).
- [x] API Method to List Users.
- [x] API Method to List Models.
- [x] API Method to Create Users.
- [x] API Method to Create Models.
- [x] API Method to Retrieve Models.
- [x] [Add .gitignore file](https://djangowaves.com/tips-tricks/gitignore-for-a-django-project/).
- [x] [API testing](https://www.django-rest-framework.org/api-guide/testing/).
- [x] [Internationalization/localization](https://phrase.com/blog/posts/quick-guide-django-i18n/). (Before error handling, so error messages can directly be implemented using i18n).
- [x] [Error handling](https://www.django-rest-framework.org/api-guide/exceptions/).
- [x] [Generate documentation](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/admindocs/).
- [x] Create readme.md file with setup instructions.

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Fixes #53 

A more detailed list of what has been done here is in #53.

In the [README.md](https://github.com/opensim-org/opensim-viewer/blob/backend/src/backend/README.md) file of the backend folder there are instructions to set the server up.

The files already existing in the backend folder were added to a new folder called files, so we don't mix them with the django files.

Right now the database is a local SQLite database, but we can switch to PostgreSQL once we are ready for deployment. In any case, I think we should keep support for SQLite in the future for local unit testing.

I added instructions to recreate the ERD diagram and migrate database and for localization, but it is not necessary unless we change the database structure or add/modify localization strings respectively.

### CODE REVIEW

**Comment by aymanhab** [comment]
added conda-forge channel to resolve.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab thank you for finding it, looks like I added the packages but I forgot about the channel.

**Comment by aymanhab** [comment]
Is it intended that there are two nested backend folders? Also localhost:8000 reports page not found, I'm possibly doing something wrong but I'm trying to follow the readme.md inside the backend folder. @AlbertoCasasOrtiz

**Comment by AlbertoCasasOrtiz** [comment]
Hi Ayman, yes, I just named both the django server and app as backend, we can change that.

Right now, http://127.0.0.1:8000/ does not exist (the only frontend existing is the admin frontend, maybe we should redirect there). But you can access to the admin site through http://127.0.0.1:8000/admin/. It is possible that you will need to migrate and create a superuser to login:

Migrate:

- `python manage.py makemigrations`
- `python manage.py migrate`

Create superuser:

- `python manage.py createsuperuser`

**Review by aymanhab — APPROVED** [review]
I'd keep a minimal .gitignore to avoid potentially missing local changes that could be relevant.

For ModelAdmin, I'd not use model_gltf_file as too limiting but we can fix later.

I'd also avoid license_link and have a few standard options as typical for public models, and make some of the other fields optional.

Can we run backend tests on commit?

Non of these is blocking so I approved the PR. Feel free to merge to move on or address feedback

**Comment by AlbertoCasasOrtiz** [comment]
Thank you @aymanhab 

> For ModelAdmin, I'd not use model_gltf_file as too limiting but we can fix later.

I have to check, but I think there is a way to store multiple files in a django database, something like ArrayField of type FileField, so we can store multiple files for a specific model. Maybe we should differentiate between user files and generated gltf file.

> I'd also avoid license_link and have a few standard options as typical for public models, and make some of the other fields optional.

I agree, maybe we can do like in addbiomechanics or opencap and use a specific license or set of licenses.

> Can we run backend tests on commit?

Definitely we want this, I will check but I am sure there is a way.

You have to approve the PR for me to merge.

**Review by aymanhab — APPROVED** [review]
LGTM, thanks @AlbertoCasasOrtiz 👍

**Pull request merged**
